# Generated by Django 6.0.3 on 2026-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_fujifilmrecipe_fujifilmexif_add_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FujifilmRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('film_simulation', models.CharField(max_length=100)),
                ('dynamic_range', models.CharField(max_length=100)),
                ('grain_roughness', models.CharField(max_length=100)),
                ('grain_size', models.CharField(max_length=100)),
                ('color_chrome_effect', models.CharField(max_length=100)),
                ('color_chrome_fx_blue', models.CharField(max_length=100)),
                ('white_balance', models.CharField(max_length=100)),
                ('white_balance_red', models.IntegerField()),
                ('white_balance_blue', models.IntegerField()),
                ('highlight', models.IntegerField()),
                ('shadow', models.IntegerField()),
                ('color', models.IntegerField()),
                ('sharpness', models.IntegerField()),
                ('high_iso_nr', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('monochromatic_color_warm_cool', models.IntegerField()),
                ('monochromatic_color_magenta_green', models.IntegerField()),
            ],
        ),
    ]
