# Generated by Django 6.0.3 on 2026-03-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_add_fujifilm_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fujifilmrecipe',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
