# Generated by Django 6.0.3 on 2026-03-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_fujifilmrecipe_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='fujifilmrecipe',
            name='d_range_priority',
            field=models.CharField(default='Off', max_length=50),
        ),
    ]
