# Generated by Django 6.0.3 on 2026-03-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_rename_recipe_add_fujifilm_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
