# Generated by Django 6.0.3 on 2026-03-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_image_in_album_image_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date_taken',
            new_name='taken_at',
        ),
    ]
